### ISSUE TITLE
Throttle not responsive

### ISSUE THREAD

**Issue by casainho** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#87] opened 2019-04-22 02:47 UTC
Tested in v0.18.2 and throttle input is used and works as expected.
Configured using menu item 8 sub menu 0 set to value 2

Tested in v0.19.3 beta and verified throttle ADC readings are fine under menu 10 sub menu 0, But no motor movement.
Enable throttle menu has changed to menu item 8 sub menu 4 set to value 2 confirmed this is correct.

**Comment by Pscope** [comment] 2019-04-25 09:10
This appears to still be an issue in v0.19.5 beta

**Comment by leon927** [comment] 2019-06-11 21:22
I have maybe missed this but is it solved in the 0.19.0 beta 8? I have no throttle to test with. Have not heard anyone having issues.

**Comment by Pscope** [comment] 2019-06-12 07:59
Hi Leon,

Sorry I am unable to test this at the moment, as the trike with the throttle 
is now with the owner, not at my location, but hopefully in the next few 
days i will have access to it to try . I will test and let you and the 
thread know. 
 Cheers Neil

**Comment by leon927** [comment] 2019-06-12 08:43
Neil, thank you!

Cheers 

Leon

**Comment by leon927** [comment] 2019-06-18 13:14
Neil, @Pscope

Sorry to bother you but have you had the chance to test the throttle? If not, it is totally fine. Just checking.

Leon

**Comment by Pscope** [comment] 2019-06-18 13:54
Hi Leon,

Sorry but no not yet :(

Unfortunately the trike is currently in a locked store I don't personally 
have the key for but i know the man who does!

I hopefully will get access to it this weekend, and will bring it home. I 
haven't forgotten, Its just not in my possession at the moment 
unfortunately. I was going to add a throttle to my own TSDZ" but I am 
running the temperature sensor so I have to open the motor to disconnect 
that to test a throttle, and well I don't really want to do that if I can 
help it.

Feel free to keep asking, I have a lot of projects on at the moment so i'm 
happy to receive a gentle reminder :)

**Comment by leon927** [comment] 2019-06-19 13:03
No problem at all and absolutely no need to install the throttle! Will also ask the thread to see if anyone has tried it out.

Based in Sweden, slightly north of you guys! ;)

Leon

**Comment by Pscope** [comment] 2019-06-20 10:50
I have the trike at home now so will test tonight and get back to you. 

Cheers

Neil

**Comment by Pscope** [comment] 2019-06-20 18:38
Hi Leon,


OK I have managed to test the throttle on 0.19.0 beta 7 and I'm afraid its 
the same.

If I now go to menu 9 item 1 I can see the throttle value change from 0 to 
255 as i twist it, so its being detected by the firmware. but nothing 
happens.

Downgrade to the last release 0.18.2 and it works.
so something in 0.19.0 has stopped it.
It's been the same through each beta release.

Cheers
Neil

**Comment by leon927** [comment] 2019-06-21 12:09
Appreciate you took the time to test!

Did you mean beta 8? I think it does not matter if it was beta 7 as the problem should be present in beta 8 as well. But just want to make sure.

I will take a look at this and once again, thank you for testing!

Leon

**Comment by Pscope** [comment] 2019-06-21 12:52
Hi Leon,  I did actually checked beta 7 last night not beta 8. I missed that 
release! doh. will check that also tonight, but like you say I don't think 
there are any changes 

Cheers
Neil

**Comment by Pscope** [comment] 2019-06-21 17:29
Success!

0.19.0 beta 8 throttle now works!

I will do some more testing but yes its looking like its fixed.

cheers
Neil

**Comment by leon927** [comment] 2019-06-21 19:04
That is actually great news! Please do test some more and let me know if you are satisfied!

And if you could make sure and double check that it is the 0.19.0 beta 8 that is uploaded both in the display and controller that would be much appreciated. 

Can not thank you enough for the feedback and testing, Neil!

Cheers,

Leon

**Comment by leon927** [comment] 2019-06-24 10:45
@Pscope - Big thanks for the help Neil! The issue is solved!

@casainho - We can now close this as it is solved in the latest beta and thereby the stable 0.19.0.

**Closed as completed** 2019-06-24 17:40 UTC
