### ISSUE TITLE
Battery SOC percentage wrongly displayed after power cycle

### ISSUE THREAD

**Issue by j0bro** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#101] opened 2019-06-11 15:32 UTC
I configured the KT-LCD3 to display the SOC as percentage in the lower right corner of the ODO field. After a full charge this displays 100, and during the ride this value decreases accordingly. 
At power up for a next ride the value mostly starts at a completely wrong value, around 40 which makes we wonder if it is not displaying the voltage as raw value instead of converted to charge percentage.
This is totally reproducible.

**Comment by leon927** [comment] 2019-06-11 18:44
What version of firmware are you using on the KT-LCD3?

**Comment by j0bro** [comment] 2019-06-11 18:54
Ah sorry forgot to mention; I am on the 0.18.2 firmware.

I rode home today from work and the same thing again - it resumed decreasing not from the actual percentage but somewhere around 40-ish. It went down to zero and stayed there. The battery indicator does show the right SOC.

**Comment by casainho** [comment] 2019-06-11 18:59
Please read carefully the wiki to make sure you did the correct configuration about the SOC (Coulomb counting).

**Comment by leon927** [comment] 2019-06-11 19:17
Will try to reproduce the problem within a couple of hours.

Will charge above the voltage threshold so everything is reset. Will ride the bike until I get below 100 percent. Then power off and see what happens.

Will test on the 0.19.0 beta 8 though. But the calculation is the same compared to 0.18.2.

**Comment by j0bro** [comment] 2019-06-11 19:30
I set menu 2:0 to value 1 (display watt-hours consumed and percentage of charge remaining ) and menu 6:0 to value 2 (Battery state of charge in percent). I have a 36V battery and just double checked while it is on the charger - I set the threshold to 41.5V but even when the display showed 41.5V or even 41.6V, the value for the SOC percentage was not resetting to 100.

I expected the value to rise while charging; like the battery indicator does even. But for some reason it is behaving erratically. Thanks in advance for testing!

**Comment by j0bro** [comment] 2019-06-11 19:33
![IMG_20190611_212620](https://user-images.githubusercontent.com/5197484/59300790-558d1780-8c90-11e9-8719-9fac4737e5e9.jpg)
This is what my display shows while charging. I set the battery-full-threshold to 41.5V and the right bottom odometer field to show the SOC percentage. See that the battery indicator (left top) does show correct value.

**Comment by leon927** [comment] 2019-06-11 19:43
No problem! :)

The SOC is only reset when you power up the display. It is a one-time check done during startup. This is why it did not reset when you have it charging and looking at the value. 

Charge the bike, power on and then it is reset to zero.

EDIT: The left top battery symbol has nothing to do with the SOC percentage. It is simply measuring the voltage and converting that to the operating range of typical lithium cells.

**Comment by j0bro** [comment] 2019-06-11 19:50
I did power cycle the display but to no avail. The value indeed remains zero, but I expected it to be set to 100 (charge went above the threshold). It would be a good thing IMHO if that SOC field is updated continuously, just like the battery indicator on the left-top. I could see if I can make a PR for that if desired.

**Comment by leon927** [comment] 2019-06-11 20:14
Just tested it and it works as expected on my short test. Could not reproduce it on version 0.19.0 beta 8. So it is very strange.

What you can do is await the official release of the 0.19.0 version. But everything should work with the 0.18.2 also. Especially as no one has reported any problems regarding this.

Try again by setting the voltage threshold to 36 volt. Power down the bike and then power back on. See if it resets. Do not have it plugged in and charging when you test this. Let me know if it worked or if you still experience that it does not reset after the set threshold voltage.

**Comment by j0bro** [comment] 2019-06-11 20:42
Ok I lowered the threshold and had the charger unplugged, power cycled and saw the value go back to 100 again. But that was not the issue - it should resume showing the correct SOC percentage after several bike rides and that is where it goes wrong for me. Will keep you updated!

**Comment by leon927** [comment] 2019-06-11 20:54
I understand that was not your original issue but that one is easy to test right now. Try it out some more and let us know how everything works.

**Comment by leon927** [comment] 2019-06-14 12:19
Hi @j0bro 

Have you tested it some more and does it work as designed?

**Comment by j0bro** [comment] 2019-06-14 14:30
Hey Leon,

Yes I rode the bike twice now and even made pictures, but after setting the
'full' threshold to something a bit lower than what I had, the issue seems
to be resolved. I think that still a live update of this value would be a
good idea, but I can live with it as it is. Please go ahead and close!

Thanks, Jeroen

Op vr 14 jun. 2019 om 14:20 schreef Leon <notifications@github.com>:

**Comment by leon927** [comment] 2019-06-24 10:47
@j0bro - Thanks for the comments and feedback Jeroen. By the way, glad to hear it is solved!

@casainho - We can now close this.

**Closed as completed** 2019-06-24 17:42 UTC

**Comment by leon927** [comment] 2019-07-07 01:55
> Hey Leon, Yes I rode the bike twice now and even made pictures, but after setting the 'full' threshold to something a bit lower than what I had, the issue seems to be resolved. I think that still a live update of this value would be a good idea, but I can live with it as it is. Please go ahead and close! Thanks, Jeroen

@j0bro The SOC is now reset live once it detects battery voltage over the threshold voltage. Should be closer to what you wished for. Look for it in the next version!

Leon
